### ISSUE TITLE
Going back with a swipe reloads page

### ISSUE THREAD

**Issue by bernatfortet** [DannyMoerkerke/whatpwacando.today#28]
Repro:
- go to homepage and navigate to any of the feature pages
- Then go back by swipe on the edge of the screen 

Results
- The bottom navigation moves with the swipe (instead of only the content section)
- after it has transitioned the whole page refreshes

Expected
- the best case would be for the navigation to stay fixed at the bottom like a native app. 
- if that's not possible then prevent the refresh. I think many website nowadays have a seamless back experience when swiping from the side.

**Comment by DannyMoerkerke** [comment]
This is a nasty bug, currently researching this. Thanks for reporting.

**Comment by softius** [comment]
I am facing the same issue. Has anyone figured out a way to overcome this or at least disable it somehow?

Unfortunately I couldn't find much resources and it looks like a tricky problem to Google :)

**Comment by DannyMoerkerke** [comment]
The reloading page issue is now fixed in Safari 18 which supports the `hasUAVisualTransition` property of the `PopStateEvent` which indicates if the UA provided a transition (which is the case when swiping back).

The only thing I can't fix yet is the sliding bottom navigation that correctly stays in place when hitting the back button but not when swiping right to go back.

I'm not (yet) sure how to fix this or if it can be fixed.
