### ISSUE TITLE
Pressing the `install to home screen` button then `close` renders scrolling useless

### ISSUE THREAD

**Issue by gaber85** [DannyMoerkerke/whatpwacando.today#45]
On the iPhone 14 pro max running iOS version 16.6.1 while using Safari to visit the homepage, pressing the `install to home screen` button and then pressing the `close` button immediately prevents the user from scrolling page.

https://github.com/DannyMoerkerke/whatpwacando.today/assets/20451159/f0c18541-d3f3-43c4-9fb5-c9ed7aed331f

**Comment by Rabithua** [comment]
It looks like some mechanism is used to prevent scroll penetration, and this mechanism is not cleared after close.

**Comment by DannyMoerkerke** [comment]
This looks like an iOS bug since I'm able to reproduce this on iOS 16.4 and 17 but not on iOS 17.2
The dialog is a native `<dialog>` element and it seems this doesn't play well with the scrolling `<div>` that has `overflow: hidden`.
I noticed that when I give it `overflow: auto` when the `<dialog>` is closed and then revert it to `overflow: hidden` with a short delay, the problem is fixed.

I deployed this fix, could you please check on your side as well?

**Comment by gaber85** [comment]
@DannyMoerkerke Yep it's working now. 👌 Thanks for the quick turnaround!
